# database settings
db:
  mysql: false


# clan pricing
clan:
  interest_rate_increase: 0.00001 # by how much interest increases every minute
  max_interest_rate: 7.0 # Maximum interest rate for the clan
  create:
    price:
      money: 100000.0
  banner:
    buy_price:
      money: 100000.0
    change_price:
      money: 100000.0
  name:
    change_price:
      money: 100000.0
# clan chat
chat-format: "<gold>➜</gold> {player}<dark_gray>:</dark_gray><gray> {message}</gray>"

# language localization for date formatting
language: "sl SI"


rank_interest_value:
  default: 0.00001
  vip: 0.000001


# random names for clans
random_clan_names:
  - "Soul Thieves"
  - "Amber Ghosts"
  - "Space Knives"
  - "Armed Tribe"
  - "Alien Amigos"
  - "Wild Jets"
  - "Exiled Bunch"
  - "Rebel Orcs"
  - "Bros n Pros"
  - "Fear United"
  - "Fangs Inc"
  - "Tasty Trash"
  - "Dark Rifles"