# database settings
db:
  mysql: false


currency:
  Vault: "money"
  VotingPlugin: "Tokens"


deposit_maxs:
  Vault: 10000000
  VotingPlugin: 10

currencies_max_interest_adding:
  Vault: 10000000.0
  VotingPlugin: 100

# clan pricing
clan:
  default_request_expire_duration: 504000 # in seconds
  max_members: 10

  tag_min_length: 1
  tag_max_length: 2

  min_name_length: 4
  max_name_length: 16 # how long can clan name be.

  update_interval: 1200 # in ticks 1 sec => 20 ticks

  default_join_price: 10000
  interest_rate_increase: 0.00001 # by how much interest increases every iteration
  max_interest_rate: 7.0 # Maximum interest rate for the clan

  create:
    price:
      money: 100000.0
  banner:
    buy_price:
      money: 100000.0
    change_price:
      money: 100000.0
  name:
    change_price:
      money: 100000.0
  tag:
    change_price:
      money: 100000.0

# clan chat
chat-format: "<gold>➜</gold> {player}<dark_gray>:</dark_gray><gray> {message}</gray>"

# language localization for date formatting
language:
  language: "sl"
  country: "SI"


default_permissions:
  - "VIEW_CLAN_INFO"
  - "VIEW_BANK"
  - "VIEW_MEMBERS"


rank_interest_value:
  default: 0.00001
  vip: 0.000001

