name: EasyClans
main: eu.virtusdevelops.easyclans.ClansPlugin
api-version: 1.19
version: @version@

depend:
  - LuckPerms
  - Vault
  - PlaceholderAPI


soft depend:
  - VotingPlugin

commands:
  clans:
    permission: clans.command.main
    aliases: ["clan"]