name: EasyClans
main: net.astrona.easyclans.ClansPlugin
api-version: 1.19
version: @version@

depend:
  - LuckPerms
  - Vault
  - PlaceholderAPI

commands:
  clans:
    permission: clans.command.main
    aliases: ["clan"]